/**
 * Contract round-trip: the /lens demo fixture is generated by the SAME Python
 * code path a real export uses (vitreous.malignancy + the HAM10000 Taxonomy via
 * apps/web/scripts/gen-lens-demo.py) — it must parse through the strict TS
 * validator and the readouts must behave (malignant cases score high, the
 * off-manifold case refuses). Producer↔consumer drift alarm.
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { parseLensJson } from "./lens";
import {
  categoryLevels,
  expectedCategory,
  malignantIndices,
  malignantProbability,
  projectFeature,
} from "./malignancy";

const FIXTURE = fileURLToPath(new URL("../../public/lens/demo.json", import.meta.url));

describe("lens demo fixture (Python-generated) round-trip", () => {
  const bundle = parseLensJson(readFileSync(FIXTURE, "utf-8"));

  it("carries the medically-correct HAM10000 taxonomy", () => {
    expect(bundle.dataset).toBe("ham10000");
    expect(bundle.class_names).toHaveLength(7);
    const mal = Object.entries(bundle.taxonomy.malignant).filter(([, m]) => m).map(([c]) => c).sort();
    expect(mal).toEqual(["Actinic keratoses", "Basal cell carcinoma", "Melanoma"]);
    expect(bundle.taxonomy.category_labels).toEqual(["benign", "in-situ", "invasive"]);
    expect(bundle.axis?.provider).toBe("malignancy_axis");
  });

  it("scores malignant example cases above benign ones", () => {
    const malIdx = malignantIndices(bundle.class_names, bundle.taxonomy);
    const mel = bundle.lesions.find((l) => l.true_label === "Melanoma")!;
    const nv = bundle.lesions.find((l) => l.true_label === "Melanocytic nevi")!;
    expect(malignantProbability(mel.probabilities, malIdx)).toBeGreaterThan(0.8);
    expect(malignantProbability(nv.probabilities, malIdx)).toBeLessThan(0.2);
  });

  it("places the in-situ case at the middle of the category axis", () => {
    const levels = categoryLevels(bundle.class_names, bundle.taxonomy);
    const akiec = bundle.lesions.find((l) => l.true_label === "Actinic keratoses")!;
    const coord = expectedCategory(akiec.probabilities, levels);
    expect(coord).toBeGreaterThan(0.5);
    expect(coord).toBeLessThan(1.5); // near the in-situ rung (level 1)
  });

  it("projects benign below malignant on the learned manifold", () => {
    const axis = bundle.axis!;
    const mel = bundle.lesions.find((l) => l.true_label === "Melanoma")!;
    const nv = bundle.lesions.find((l) => l.true_label === "Melanocytic nevi")!;
    expect(projectFeature(mel.feature, axis).position).toBeGreaterThan(0.6);
    expect(projectFeature(nv.feature, axis).position).toBeLessThan(0.4);
  });

  it("refuses the off-manifold (phone-photo stand-in) case", () => {
    const axis = bundle.axis!;
    const off = bundle.lesions.find((l) => l.id === "case_offmanifold_phone")!;
    const inDist = bundle.lesions.find((l) => l.true_label === "Melanoma")!;
    expect(projectFeature(off.feature, axis).ood).toBe(true);
    expect(projectFeature(inDist.feature, axis).ood).toBe(false);
  });

  it("every lesion has decodable thumbnail + full-width softmax", () => {
    for (const l of bundle.lesions) {
      expect(l.probabilities).toHaveLength(bundle.class_names.length);
      const head = Buffer.from(l.thumb_png_b64, "base64").subarray(0, 4);
      expect(Array.from(head)).toEqual([0x89, 0x50, 0x4e, 0x47]);
    }
  });
});
