/**
 * Contract round-trip: the bundled /sgp demo fixture — generated by the SAME
 * Python code path a real Kaggle run uses (vitreous.som via
 * apps/web/scripts/gen-sgp-demo.py) — must parse cleanly through the strict TS
 * validator. This is the producer↔consumer drift alarm (mirrors
 * PackClient.fixture.test.ts).
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { depthActivations, migrationCurve, parseSgpJson } from "./sgp";

const FIXTURE = fileURLToPath(new URL("../../public/sgp/demo.json", import.meta.url));

describe("sgp demo fixture (Python-generated) round-trip", () => {
  const bundle = parseSgpJson(readFileSync(FIXTURE, "utf-8"));

  it("parses with the documented HAM10000-preset geometry", () => {
    expect(bundle.som.grid).toEqual([8, 8, 8]);
    expect(bundle.som.num_neurons).toBe(512);
    expect(bundle.som.depth_steps).toBe(8);
    expect(bundle.som.volume_grid).toEqual([16, 16]);
    // 6-connected 8³ lattice: 3 · 7 · 8 · 8 face edges.
    expect(bundle.som.edges).toHaveLength(3 * 7 * 8 * 8);
    expect(bundle.probes.length).toBeGreaterThan(0);
  });

  it("is a mostly-live map with dead neurons flagged consistently", () => {
    const dead = bundle.som.nodes.filter((n) => n.dead).length;
    expect(dead).toBe(bundle.som.dead_neurons);
    expect(dead / bundle.som.num_neurons).toBeLessThan(0.5);
    for (const n of bundle.som.nodes) expect(n.dead).toBe(n.hits === 0);
  });

  it("derives well-formed activations + migration for every probe", () => {
    for (const p of bundle.probes) {
      const acts = depthActivations(p.bmu, bundle.som.num_neurons);
      expect(acts).toHaveLength(bundle.som.depth_steps);
      for (const a of acts) {
        let s = 0;
        for (const v of a) s += v;
        expect(s).toBeCloseTo(1, 5);
      }
      const mig = migrationCurve(p.bmu);
      expect(mig).toHaveLength(bundle.som.depth_steps - 1);
      for (const m of mig) {
        expect(m).toBeGreaterThanOrEqual(0);
        expect(m).toBeLessThanOrEqual(1);
      }
    }
  });

  it("carries a decodable PNG thumbnail per probe", () => {
    for (const p of bundle.probes) {
      const head = Buffer.from(p.thumb_png_b64, "base64").subarray(0, 8);
      expect(Array.from(head)).toEqual([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);
    }
  });
});
